### ISSUE TITLE
As full administrator, I cannot propose changes to Control List Administators

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pyrrha#135]
## Current Behaviour

![image](https://user-images.githubusercontent.com/1929830/60800457-83715900-a175-11e9-9a0a-ffb1891c6535.png)

0. As a non owner of the control list and as administrator
1. For a Control List, click the Control List top menu, select a control list. 
2. On the left menu bar, there is no links (if the CL is not public), or there is a link to make it public

## Expected behaviour

I should see the <kbd>Propose Change</kbd> link under other to send a mail to list administrator

**Comment by carinedengler** [comment]
We estimated this ticket to take 0.5d.

**Comment by carinedengler** [comment]
We do not seem to be able to reproduce this bug on either of our local instances, we tried

* as administrator, but not owner on both a public and a private list -> the link to propose changes is there
* as administrator and owner on both a public and a private list -> the link to propose changes is not there

This seems to be the expected behavior for this link as described by you.

However, we always have at least two buttons on the left-hand side menu, one to rename the list and one to modify its related information, whereas the button to make it public (if it is private) is not in that menu at all, but in the `controls` view. Our instances are at the top of the dev branch.

**Comment by MrGecko** [comment]
The current behavior present in 
https://github.com/hipster-philology/pyrrha/blob/dev/app/templates/control_lists/macros.html 
is the following (content truncated for clarity purpose):
```html      
      {% if not control_list.can_edit() %}
      Propose changes
      {% endif %}

      {%  if control_list.can_edit() and not current_user.is_admin() %}
      Make public
      {% endif %}

      {%  if control_list.can_edit() or current_user.is_admin() %}
      Rename
      {% endif %}

      {%  if control_list.can_edit() or current_user.is_admin() %}
      Edit informations
      {% endif %}
```

Therefore if you can edit, you cannot propose change (thus you don't see the link).

@PonteIneptique  I have a hard time to reproduce the "no link at all" case.

**Comment by carinedengler** [comment]
When I try to reproduce the issue, I have the following user interface

![control-list-lemma-admin](https://user-images.githubusercontent.com/56160522/94669234-4280d980-0311-11eb-80f3-d69191ba161c.png)

In that case, I am admin, and it's a public control list. If it's a private control list of which, I, as admin, am not the owner, I have this user interface

![control-list-pos-admin-private](https://user-images.githubusercontent.com/56160522/94669689-db175980-0311-11eb-9d58-4c5c0e4aaf56.png)

In both cases, the link to propose changes is visible and clickable, and the control lists in question are editable. I am on the head of the `dev` branch, and haven't implemented any changes.

**Comment by PonteIneptique** [comment]
I think "Propose changes" should be always on. That will "fix" this issue.
