### ISSUE TITLE
Ability to change order of the search results

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pyrrha#137]
Right now, order of the text, Would be great to be able to order by form, lemma, pos, morph, desc and asc. :)

**Comment by carinedengler** [comment]
flask does not seem to natively support sortable columns; after investigating the issue for a bit, I could think of two possible solutions

**using [flask-table](https://github.com/plumdog/flask_table) to create [sortable tables](https://github.com/plumdog/flask_table)**

pros
* tables are sortable by headers
* tables are handled in Python instead of HTML

cons
* last updates to project date from 2 years ago (however, the maintainer himself seems to be still [active](https://github.com/plumdog))
* implies rewriting current table handling
* adds dependency

**adding an option to the search form indicating the desired order criteria**

(in the form of an additional column, a button ... ?)

pros
* no third party dependency necessary
* no rewrite of the existing necessary

cons
* very unusual, the users are probably more used to sortable columns
* every time the user wants the results ordered differently, the paginated results need to be reevaluated

**Comment by PonteIneptique** [comment]
Hey :)
I definitely think this should be done through the SQL Query, with some addenda to the HTML `<thead>` element :)

We'll probably migrate to a better and cleaner JS system later (Vue I assume) so I would absolutely avoid Flask-Table :) And I am not even speaking about the editable rows we have, and the work it would create right now to move to flask table regarding this :)

What's your opinion on the cons @Jean-Baptiste-Camps ? What's your opinion on my opinion @MrGecko ? :)

**Comment by carinedengler** [comment]
I threw something together for the ui (quick and dirty), which one would you prefer (or would you prefer something else entirely?)
1. [buttons after form, before search results](https://extranet.logilab.fr/upload/file.php?h=Rc3659e976e7ca1e867dd8371a7e61117)
2. [buttons before form](https://extranet.logilab.fr/upload/file.php?h=Rbef0485525dbd6b8bec9e1f9886419fc)

(of course color, positioning and labels of the buttons can be adapted, I just want to know if I got the general idea right)
if we go with this solution, I would say that I need about one workday for the implementation and 0.5 for adding tests and testing

**Comment by MrGecko** [comment]
As mentioned earlier by @PonteIneptique, I think these buttons could easily fit in the ```<thead>``` cells.
I also agree this is only a matter of adding an ```order by``` clause to the sqlalchemy query on the backend side. It will indeed reevaluate the pagination, but that's ok. 

The sort should stay mono criteria at the moment, which is what your solution shows :+1: .
Be aware that we may want to add this sort feature to future tables so it would be nice to make it as reusable as possible.
